ENV JDK=%VERSION%

# Temporary workaround https://github.com/docker-library/openjdk/issues/101
RUN bash -c '([[ ! -d $JAVA_SECURITY_DIR ]] && ln -s $JAVA_HOME/lib $JAVA_HOME/conf) || (echo "Found java conf dir, package has been fixed, remove this hack"; exit -1)'
