#!/bin/bash -e

NAME="gradle"
DISPLAY_NAME="Gradle"
FROM="gradle:%VERSION%-jdk8"
TYPE="s2i"
VARIANTS="default"
VERSIONS="3.5"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
