#!/bin/bash -e

NAME="gradle"
DISPLAY_NAME="Gradle"
FROM="gradle:%VERSION%"
TYPE="s2i"
VARIANTS="default"
VERSIONS="jdk8,jdk9"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
